kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoints-list-binding
  namespace: development
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: endpoints-list
  apiGroup: ""
