
	# $(location)/script/99_cleanup.sh
	# echo -e  "************"
	# echo -e  "When spinning up a cluster, a config file is created within `~/.kube/"
	# echo -e  "This is the default configuration used by Kubectl to connect to a cluster"
	# echo -e  "Let's look at the file"
	# echo -e  "************"
	# echo -e  ""
	# read  -n 1 -p "Press any key to continue..."